server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*-json.log

    # Extract Docker metadata
    pipeline_stages:
      - json:
          expressions:
            stream: stream
            attrs: attrs
            tag: attrs.tag
      - labels:
          stream:
          tag:
      - regex:
          expression: (?P<container_id>(?:[0-9a-f]{64}|[0-9a-f]{12}))
          source: filename
      - docker:
          container_name_label: container_name
          stream_label: stream
      - timestamp:
          source: time
          format: RFC3339Nano
