groups:
  - name: host_alerts
    rules:
      # Host CPU alert - combined into single alert with severity levels
      - alert: HighCPULoad
        expr: 100 - (avg by(host) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU load on {{ $labels.host }}"
          description: 'CPU load is above 80% for 5 minutes (current value: {{ $value | printf "%.2f" }}%)'
          dashboard: "https://monitor01.cw.internal:3000/d/server-cluster-overview"

      # Host memory alert - combined into single alert
      - alert: LowMemory
        expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100 < 15
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Low memory on {{ $labels.host }}"
          description: 'Node memory is filling up (< 15% left) (current value: {{ $value | printf "%.2f" }}%)'
          dashboard: "https://monitor01.cw.internal:3000/d/server-cluster-overview"

      # Host disk space alert - combined into single alert
      - alert: LowDiskSpace
        expr: (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"} * 100) < 15
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Low disk space on {{ $labels.host }}"
          description: 'Disk space is below 15% (current value: {{ $value | printf "%.2f" }}%)'
          dashboard: "https://monitor01.cw.internal:3000/d/server-cluster-overview"

  - name: container_alerts
    rules:
      # Container alerts - reduced to essential monitoring
      - alert: ContainerDown
        expr: count by(name, host) (container_last_seen{name=~".+"}) unless count by(name, host) (container_last_seen{name=~".+"} offset 5m)
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Container {{ $labels.name }} on {{ $labels.host }} is down"
          description: "Container {{ $labels.name }} is not running"
          dashboard: "https://monitor01.cw.internal:3000/d/container-monitoring"

      # Container restart alerts
      - alert: ContainerRestarting
        expr: changes(container_start_time_seconds[15m]) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Container {{ $labels.name }} on {{ $labels.host }} restarting"
          description: "Container {{ $labels.name }} has restarted {{ $value }} times in the last 15 minutes"
          dashboard: "https://monitor01.cw.internal:3000/d/container-monitoring"

  - name: service_alerts
    rules:
      # Service availability - kept simple
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} on {{ $labels.host }} is down"
          description: "Service {{ $labels.job }} on {{ $labels.host }} has been down for more than 1 minute."
          dashboard: "https://monitor01.cw.internal:3000/d/server-cluster-overview"

  - name: nginx_alerts
    rules:
      # Simplified Nginx alerts - focusing on key metrics
      - alert: NginxHighErrorRate
        expr: sum(rate(nginx_http_requests_total{status=~"5.."}[5m])) / sum(rate(nginx_http_requests_total[5m])) * 100 > 5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High Nginx error rate on {{ $labels.host }}"
          description: 'Nginx error rate is above 5% for 5 minutes (current value: {{ $value | printf "%.2f" }}%)'
          dashboard: "https://monitor01.cw.internal:3000/d/nginx-monitoring"

      # Detect potential scanning/brute force attempts
      - alert: NginxPotentialScanningActivity
        expr: sum by(remote_addr) (count_over_time({job="nginx", status="404"}[5m])) > 20
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Potential scanning from IP {{ $labels.remote_addr }}"
          description: "IP {{ $labels.remote_addr }} has generated {{ $value }} 404 errors in the last 5 minutes, which may indicate scanning activity"
          dashboard: "https://monitor01.cw.internal:3000/d/nginx-monitoring"
