global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - "alert-rules.yml"

scrape_configs:
  # Monitoring Server (${MONITOR_HOST}) - Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          host: "${MONITOR_HOST}"
          instance_group: "monitoring"

  # Monitoring Server (${MONITOR_HOST}) - Node Exporter
  - job_name: "${MONITOR_HOST}-node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
        labels:
          host: "${MONITOR_HOST}"
          instance_group: "monitoring"

  # Monitoring Server (${MONITOR_HOST}) - cAdvisor
  - job_name: "${MONITOR_HOST}-cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
        labels:
          host: "${MONITOR_HOST}"
          instance_group: "monitoring"

  # Dev Server (${DEV_HOST}) - Node Exporter
  - job_name: "${DEV_HOST}-node-exporter"
    static_configs:
      - targets: ["${DEV_HOST}:9100"]
        labels:
          host: "${DEV_HOST}"
          instance_group: "application"

  # Dev Server (${DEV_HOST}) - cAdvisor
  - job_name: "${DEV_HOST}-cadvisor"
    static_configs:
      - targets: ["${DEV_HOST}:8080"]
        labels:
          host: "${DEV_HOST}"
          instance_group: "application"

  # Frontend Server (${FRONTEND_HOST}) - Node Exporter
  - job_name: "${FRONTEND_HOST}-node-exporter"
    static_configs:
      - targets: ["${FRONTEND_HOST}:9100"]
        labels:
          host: "${FRONTEND_HOST}"
          instance_group: "frontend"

  # Frontend Server (${FRONTEND_HOST}) - cAdvisor
  - job_name: "${FRONTEND_HOST}-cadvisor"
    static_configs:
      - targets: ["${FRONTEND_HOST}:8080"]
        labels:
          host: "${FRONTEND_HOST}"
          instance_group: "frontend"
