global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - "alert-rules.yml"
  - "recording-rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  # Remote EC2 instance monitoring
  - job_name: "remote-node-exporter"
    static_configs:
      - targets: ["ec2-instance-ip:9100"]
        labels:
          instance: ec2-instance-name

  - job_name: "remote-cadvisor"
    static_configs:
      - targets: ["ec2-instance-ip:8080"]
        labels:
          instance: ec2-instance-name

  # Optional: Include Docker daemon metrics
  - job_name: "docker"
    static_configs:
      - targets: ["ec2-instance-ip:9323"] # Requires Docker daemon configured with metrics endpoint
