apiVersion: 1

datasources:
  - name: Alertmanager
    type: alertmanager
    uid: alertmanager
    url: http://alertmanager:9093
    access: proxy
    jsonData:
      implementation: prometheus
    editable: true
